### ISSUE TITLE
Would be nice to see Watts used

### ISSUE THREAD

**Issue by wkoszek** [pawl/raspberry-pi-1u-server#6]
You mention having Kill-a-Watt, but don't report on total number of Watts used during the test. Would be nice to see what it ended up being

**Comment by pawl** [comment]
@wkoszek The “total” amp numbers in this section are from the kill-a-watt: https://github.com/pawl/raspberry-pi-1u-server#power-usage

If you need watts, you can use ohms law to figure that out since amps and voltage is given.

**Comment by pawl** [comment]
@wkoszek I added watts used here: https://github.com/pawl/raspberry-pi-1u-server/commit/2a3d8ef224501270450bc563172f7c48dc7ecc32
